use_frameworks!

platform :ios, '8.0'

target 'MJSensitiveWordTools_Example' do
  pod 'MJSensitiveWordTools', :path => '../'

  target 'MJSensitiveWordTools_Tests' do
    inherit! :search_paths

    
  end
end
