source 'git@git.musjoy.com:PodSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'

target 'MJSensitiveWordTools_Example' do
  pod 'MJSensitiveWordTools', :path => '../'

#  pod 'FileSource'                    # 文件操作

end
